spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/carrental?serverTimezone=GMT%2B8
  jackson:
    default-property-inclusion: non_null
  resources:
    static-locations:
      -file:///${prop.upload.base-path}

server:
  port: 8888
#跨域请求
prop:
  staticAccess: /file
  upload:
    base-path: D:/Project/IdeaProject/
    upload-path: upload/
    image-path: img/
    uploadFullPath: D:/Project/IdeaProject/upload
  web:
    cors-origins:
      - http://localhost:63342
mybatis-plus:
  global-config:
    db-config:
#      主键策略：自增
      id-type: auto
  #      起别名
  type-aliases-package: com.zz.pojo
logging:
  level:
    com.zz: debug



